### ISSUE TITLE
History bugs and (many) other bugs

### ISSUE THREAD

**Issue by stubb** [fifengine/fifengine-editor#13]
_From @prock-fife on February 6, 2010 5:8_

This issue was reported by **trendy**

Open map and history window:

Place an instance
- move instance (multiple times)
- undo once -» an instance appears at first position
- undo all -» removes this new-old instance, the moved one remains
  - if you replaced something now they have the default instance (black)

Close/Open map
- move something around
- undo is only for show

Clicking again in same place repeats the action (maybe only left clicking: '''i'''nsert,'''r'''emove,'''m'''ove), also you can move nothing (default,black) around.

If you resize the window selecting an entry resizes only the entry list to default dimensions(h&v).

Right clicking (i mode) places a history event for every instance, left clicking only for group action.

Moving with right click doesn't leave traces (no event in history).

_Copied from original issue: fifengine/fifengine#452_

**Comment by stubb** [comment]
_From @prock-fife on February 6, 2010 5:17_

This comment was posted by **trendy**

On right click (move mode) without previous action (right after loading map or after some undo) might crash the editor

```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: __import__ not found
Catched director exception
mouseDragged <fife.fife.MouseEvent; proxy of <Swig Object of type 'FIFE::MouseEv
ent *' at 0x09EFBB48> >
Traceback (most recent call last):
  File "C:\Python26x86\lib\site-packages\fife\extensions\pychan\events.py", line
 159, in _redirectEvent
    timer.delayCall(0,delayed_f)
  File "C:\Python26x86\lib\site-packages\fife\extensions\fife_timer.py", line 10
1, in delayCall
    timer.callback = cbwa(real_callback, callback, timer)
  File "C:\Python26x86\lib\site-packages\fife\extensions\fife_timer.py", line 96
, in cbwa
    c(*args)
  File "C:\Python26x86\lib\site-packages\fife\extensions\fife_timer.py", line 99
, in real_callback
    c()
  File "C:\Python26x86\lib\site-packages\fife\extensions\pychan\events.py", line
 158, in delayed_f
    f( event )
  File "C:\Python26x86\lib\site-packages\fife\extensions\pychan\events.py", line
 308, in captured_f
    tools.applyOnlySuitable(self_ref().callbacks[group_name][event_name],event=e
vent,widget=self_ref().widget_ref())
  File "C:\Python26x86\lib\site-packages\fife\extensions\pychan\tools.py", line
56, in applyOnlySuitable
    return func(*args,**kwargs)
  File "C:\FIFE2\tools\editor\scripts\editor.py", line 453, in __sendMouseEvent
    mouseDragged.send(sender=self._maparea, event=event)
  File "C:\FIFE2\tools\editor\scripts\events\signal.py", line 186, in send
    response = pychan.tools.applyOnlySuitable(receiver, signal=self, sender=send
er, **named)
  File "C:\Python26x86\lib\site-packages\fife\extensions\pychan\tools.py", line
60, in applyOnlySuitable
    return func(*args,**kwargs)
  File "C:\FIFE2\tools\editor\scripts\gui\mapeditor.py", line 411, in mouseDragg
ed
    self._controller.moveInstances(self._instances, position-self._lastDragPos,
False)
  File "C:\FIFE2\tools\editor\scripts\mapcontroller.py", line 302, in moveInstan
ces
    newCoords = loc.getLayerCoordinates() + moveBy
  File "C:\Python26x86\lib\site-packages\fife\fife.py", line 6885, in getLayerCo
ordinates
    return _fife.Location_getLayerCoordinates(self, *args)
RuntimeError: _[NotSet]_ , Cannot get layer coordinates, layer is not initialize
d properly
#####  repeated many times
```

**Comment by stubb** [comment]
_From @prock-fife on June 3, 2010 10:13_

moving to 0.3.3.  Needs to be confirmed.

**Comment by stubb** [comment]
_From @prock-fife on June 9, 2010 6:31_

This comment was posted by **trendy**

move mode right click after opening shooter map(no crash)

**Comment by stubb** [comment]
_From @prock-fife on June 9, 2010 7:19_

This comment was posted by **trendy**

```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: __import__ not found
```

repeated many times in the console (the editor was started with output redirected to the log) - see [http://fife.trac.cvsdude.com/engine/attachment/ticket/452/moveModeRightClick.log moveModeRightClick.log]

Moving with right click now makes too many events in history (even without moving to another tile area, just by movement of the mouse). It should check if you did a change or not (only events that changed something are usefull) - this should fix most of them

The first two are unconfirmed. I think they have been fixed - probably the global instance change (the problem was losing the instance)
