### ISSUE TITLE
AttributeError: 'Engine' object has no attribute 'this'

### ISSUE THREAD

**Issue by milandamen** [fifengine/fifengine-editor#24]
When I try to run the editor I get this error:

```
milan@Some-Laptop-Kubuntu:~/opt/fifengine-editor$ python2 run.py 
Using the FIFE python module found here:  /usr/lib/python2.7/dist-packages/fife                                                       
Traceback (most recent call last):                                                                                                    
File "run.py", line 43, in <module>                                                                                                 
    app = Editor(options, mapfile)                                                                                                    
File "/home/milan/opt/fifengine-editor/scripts/editor.py", line 112, in __init__                                                    
    PychanApplicationBase.__init__(self, TDS, *args, **kwargs)                                                                        
File "/usr/lib/python2.7/dist-packages/fife/extensions/pychan/pychanbasicapplication.py", line 68, in __init__                      
    super(PychanApplicationBase, self).__init__(setting)                                                                              
File "/usr/lib/python2.7/dist-packages/fife/extensions/basicapplication.py", line 75, in __init__                                   
    self.engine = fife.Engine()                                                                                                       
File "/usr/lib/python2.7/dist-packages/fife/fife.py", line 2704, in __init__                                                        
    self.this.append(this)                                                                                                            
AttributeError: 'Engine' object has no attribute 'this'
```

**Comment by LinuxDonald** [comment]
What version of swig are you using?

**Comment by milandamen** [comment]
I'm using swig 3.0.8-0ubuntu3, which is the newest for my OS (Kubuntu).

**Comment by LinuxDonald** [comment]
Swig is broken in version 3.0.8 please use 3.0.7 or 3.0.9 or higher version. That is not an fife bug.

**Comment by milandamen** [comment]
When I use 3.0.10 it gives me the same error.

**Comment by LinuxDonald** [comment]
Have you recompiled fife with swig 3.0.10?

**Comment by milandamen** [comment]
Thank you, that fixed it.

**Comment by LinuxDonald** [comment]
Np :-)
