### ISSUE TITLE
running editor causes error

### ISSUE THREAD

**Issue by chriscamacho** [fifengine/fifengine-editor#30]
Not used fifengine before, could be me...

that said everything builds just fine, and the rio de hola demo runs 

`
Controller:LOG:Engine initialized
Traceback (most recent call last):
  File "run.py", line 44, in <module>
    app.run()
  File "/usr/lib/python2.7/site-packages/fife/extensions/basicapplication.py", line 207, in run
    retval = self.mainLoop()
  File "/usr/lib/python2.7/site-packages/fife/extensions/basicapplication.py", line 230, in mainLoop
    self._pump()
  File "/home/chris/development/fife/fifengine-editor/scripts/editor.py", line 492, in _pump
    self._initGui()
  File "/home/chris/development/fife/fifengine-editor/scripts/editor.py", line 130, in _initGui
    MainWindow.initGui(self, screen_width, screen_height)
  File "/home/chris/development/fife/fifengine-editor/scripts/gui/mainwindow.py", line 68, in initGui
    self._dockareas[DOCKAREA['left']] = DockArea("left")
  File "/home/chris/development/fife/fifengine-editor/scripts/gui/dockarea.py", line 40, in __init__
    self.vexpand=0
  File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/widgets/widget.py", line 1140, in _setVExpand
    self.real_widget.setVerticalExpand(expand)
  File "/usr/lib/python2.7/site-packages/fife/fifechan.py", line 670, in setVerticalExpand
    return _fifechan.Widget_setVerticalExpand(self, expand)
TypeError: in method 'Widget_setVerticalExpand', argument 2 of type 'bool'
`

**Comment by Niektory** [comment]
Unfortunately the editor doesn't work with the current git master at the moment. For now you'll have to use an older version if you want to use the editor (the last release version should work).

**Comment by prock-fife** [comment]
We should probably tag the editor to be in line with last fife release.   Same with the demos.
